<a href="https://colab.research.google.com/github/manishgurungxon/Pythonprojects/blob/main/ANN%26CNNusingTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This time we will check ANN and CNN
# ANN : Artificial Network Neural
# CNN : Convolution Network Neural
# RNN : Recurring Network Neural

In [2]:
# we are importing the libs we will need
import tensorflow as tf # you can check the version of tensorflow with tf.__version__
import pandas as pd
import numpy as np


In [3]:
#let's import dataset
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
# Now we need to check our data info using .info() or .describe() or .shape
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:

#df.shape

In [6]:
#new_df = df.drop(["CustomerId","Gender","Age","CreditScore","Surname"], axis = 1)

In [7]:
#df

In [8]:
# finding and separating our columns 
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [9]:
#Check the values in arrays
X,y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

#**Deep learning**


In [10]:
#Since we have non numerical values in our array we have to use LabelEncoder so that our machine can understand it
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #2 is the column we want to convert since it has only yes or no or M or F values

In [11]:
#Converting 'country' column with OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')

X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size= 0.8, test_size= 0.2, random_state= 0) 

In [13]:
# Apply feature scaling on our columns
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # replacing existing value to new value 
X_test = sc.transform(X_test)


#**Now Applying our ANN**



#**xxxxxxxxxxxxxxxxxx**
# Let's build ANN
#**xxxxxxxxxxxxxxxxxx**


In [14]:
# Now lets build our ANN
ann = tf.keras.models.Sequential()


In [15]:
# We are now going to add a input layer and work on our first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# now lets add second layer by using the same function as above
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [17]:
# Now I want to add an output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #sigmoid function

In [18]:
# Okay, we have our input, hidden layers , and an output layer
# we need to compile it all
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
# training model
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.8630
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8624
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8625
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8619
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8627
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3311 - accuracy: 0.8636
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8627
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8630
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8637
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3304 - accura